// Mock data for themyungdang (real-estate for franchise spaces).
// Mirrors the shape we'd get from the Listings table once Supabase is live.

export type ListingType = 'transfer' | 'new' | 'sale'

export interface MockListing {
  id: string
  type: ListingType
  title: string
  status: 'active' | 'pending' | 'completed'
  region: string
  district: string
  fullAddress: string
  areaKey?: string
  area: number // 평
  floor: string
  buildingType: string
  rightFee?: number
  deposit: number
  monthlyRent: number
  salePrice?: number
  fitCategories: string[]
  currentBusiness?: string
  monthlyRevenue?: number
  revenueVerified?: boolean
  tags: string[]
  footTraffic: number
  availableFrom: string
  verified: boolean
  featured: boolean
  viewCount: number
  inquiryCount: number
  createdAt: string
  ownerType: 'direct' | 'agent'
  agencyName?: string
  imageColors: string[]
}

export interface MockArea {
  key: string
  name: string
  region: string
  district: string
  description: string
  /** 일 평균 유동인구 (명) */
  footTraffic: number
  /** 평당 평균 월세 (만원) */
  avgMonthlyRentPerPyeong: number
  /** 평균 권리금 (만원) */
  avgRightFee: number
  /** 평균 보증금 (만원) */
  avgDeposit: number
  /** 주요 업종 비중 */
  topCategories: Array<{ key: string; label: string; share: number }>
  highlights: string[]
  cautions: string[]
}

export interface ListingCategory {
  key: string
  label: string
  brandRefCount: number
}

export const LISTING_CATEGORIES: ListingCategory[] = [
  { key: 'chicken', label: '치킨', brandRefCount: 142 },
  { key: 'cafe', label: '카페', brandRefCount: 318 },
  { key: 'korean', label: '한식', brandRefCount: 87 },
  { key: 'japanese', label: '일식', brandRefCount: 54 },
  { key: 'snack', label: '분식', brandRefCount: 76 },
  { key: 'dessert', label: '디저트', brandRefCount: 49 },
  { key: 'beverage', label: '음료', brandRefCount: 62 },
  { key: 'bar', label: '주점', brandRefCount: 38 },
  { key: 'convenience', label: '편의점', brandRefCount: 24 },
  { key: 'education', label: '교육', brandRefCount: 41 },
]

export const TYPE_LABEL: Record<ListingType, string> = {
  transfer: '양도',
  new: '신규 임대',
  sale: '매각',
}

export const AREAS: MockArea[] = [
  {
    key: 'gangnam',
    name: '강남역 상권',
    region: '서울',
    district: '강남구',
    description:
      '국내 최상위 사무 + 유흥 복합 상권. 객단가가 높고 회전율이 좋지만 임대료 부담도 가장 큽니다.',
    footTraffic: 92000,
    avgMonthlyRentPerPyeong: 22,
    avgRightFee: 8500,
    avgDeposit: 9000,
    topCategories: [
      { key: 'cafe', label: '카페', share: 28 },
      { key: 'korean', label: '한식', share: 18 },
      { key: 'bar', label: '주점', share: 16 },
      { key: 'japanese', label: '일식', share: 12 },
    ],
    highlights: [
      '오피스 점심 + 저녁 + 심야까지 객수가 끊기지 않음',
      '대형 브랜드와 신규 브랜드가 공존하는 트렌드 시험장',
    ],
    cautions: [
      '평당 월세가 다른 상권의 2-3배. 매출이 평균 이상이어도 손익이 빠듯할 수 있음',
      '공시 매물보다 부동산 직접 협상으로 거래되는 비율이 높아 정보 비대칭이 큼',
    ],
  },
  {
    key: 'hongdae',
    name: '홍대 상권',
    region: '서울',
    district: '마포구',
    description:
      'SNS·트렌드 매장이 집중되는 20-30대 상권. 디저트·카페·캐주얼 다이닝 매장이 강세입니다.',
    footTraffic: 74000,
    avgMonthlyRentPerPyeong: 18,
    avgRightFee: 5500,
    avgDeposit: 6500,
    topCategories: [
      { key: 'cafe', label: '카페', share: 32 },
      { key: 'dessert', label: '디저트', share: 18 },
      { key: 'snack', label: '분식', share: 15 },
      { key: 'bar', label: '주점', share: 14 },
    ],
    highlights: ['SNS 노출 효과가 큰 입지', '관광객 비중 25% 이상으로 평일·주말 매출 차이가 작음'],
    cautions: ['매물 교체 주기가 빠릅니다 — 평균 보증금 회수 기간 2.8년', '소음·민원 발생 빈도가 높음'],
  },
  {
    key: 'pangyo',
    name: '판교 IT 단지',
    region: '경기',
    district: '성남시 분당구',
    description:
      '국내 대형 IT 본사 밀집 지역. 평일 점심·저녁 객수가 안정적이지만 주말 매출은 약한 편.',
    footTraffic: 48000,
    avgMonthlyRentPerPyeong: 16,
    avgRightFee: 4500,
    avgDeposit: 5500,
    topCategories: [
      { key: 'cafe', label: '카페', share: 30 },
      { key: 'korean', label: '한식', share: 22 },
      { key: 'snack', label: '분식', share: 12 },
      { key: 'japanese', label: '일식', share: 11 },
    ],
    highlights: ['평일 점심 객수가 매우 안정적', '신축 상가 비율이 높아 시설 컨디션 좋음'],
    cautions: ['주말 매출이 평일의 50% 수준 — 평일 매출로 손익 맞춰야 함', '대기업 구내식당 경쟁'],
  },
  {
    key: 'songdo',
    name: '송도 신도시',
    region: '인천',
    district: '연수구 송도동',
    description:
      '아파트 단지 + 신축 상가 + 외국인 거주 비중이 높은 신도시 상권. 가족 단위 객수 강세.',
    footTraffic: 32000,
    avgMonthlyRentPerPyeong: 13,
    avgRightFee: 2800,
    avgDeposit: 4200,
    topCategories: [
      { key: 'cafe', label: '카페', share: 26 },
      { key: 'korean', label: '한식', share: 20 },
      { key: 'snack', label: '분식', share: 14 },
      { key: 'chicken', label: '치킨', share: 13 },
    ],
    highlights: ['신축 상가라 시설 추가 비용이 적음', '주거 + 직장 + 외국인 객수 균형'],
    cautions: ['평일 점심 의존도가 낮은 만큼 회전 시간이 길어짐', '신도시 특성상 상권 안정화에 1-2년'],
  },
  {
    key: 'seomyeon',
    name: '서면 상권',
    region: '부산',
    district: '부산진구',
    description: '부산 중심 상권. 1·2층 노출 좋은 매물이 인기가 많고 저녁 매출 비중이 큼.',
    footTraffic: 65000,
    avgMonthlyRentPerPyeong: 15,
    avgRightFee: 4200,
    avgDeposit: 5500,
    topCategories: [
      { key: 'bar', label: '주점', share: 24 },
      { key: 'korean', label: '한식', share: 22 },
      { key: 'cafe', label: '카페', share: 16 },
      { key: 'japanese', label: '일식', share: 13 },
    ],
    highlights: ['관광 + 현지 객수가 균형', '저녁 + 심야 객수 강세로 주점·다이닝에 유리'],
    cautions: ['주말 매출 의존도 + 시즌 변동성 큼', '인접 상권과 경쟁이 치열'],
  },
  {
    key: 'dongseongro',
    name: '동성로 상권',
    region: '대구',
    district: '중구',
    description: '대구 최대 상권. 10대-20대 객수가 많고 패션·F&B가 함께 자리잡은 곳.',
    footTraffic: 58000,
    avgMonthlyRentPerPyeong: 14,
    avgRightFee: 3800,
    avgDeposit: 5000,
    topCategories: [
      { key: 'snack', label: '분식', share: 22 },
      { key: 'cafe', label: '카페', share: 20 },
      { key: 'bar', label: '주점', share: 15 },
      { key: 'dessert', label: '디저트', share: 12 },
    ],
    highlights: ['학생 + 직장인 객수의 균형', '대구 외 지역에서도 방문하는 광역 상권'],
    cautions: ['10-20대 객수가 많아 객단가 한계가 있음', '폐점율은 평균보다 다소 높음'],
  },
  {
    key: 'chungjangro',
    name: '충장로 상권',
    region: '광주',
    district: '동구',
    description: '광주 핵심 상권. 권리금·임대료가 광주 내 가장 높지만 객수 안정성도 가장 높음.',
    footTraffic: 42000,
    avgMonthlyRentPerPyeong: 12,
    avgRightFee: 2800,
    avgDeposit: 3800,
    topCategories: [
      { key: 'cafe', label: '카페', share: 28 },
      { key: 'snack', label: '분식', share: 18 },
      { key: 'korean', label: '한식', share: 16 },
      { key: 'dessert', label: '디저트', share: 12 },
    ],
    highlights: ['광주광역시 객수의 30% 이상이 집중', '주말·평일 객수 균형이 좋음'],
    cautions: ['신축 상가가 적어 시설 보강 비용 필요', '권리금 평균이 빠르게 상승 중'],
  },
  {
    key: 'dunsan',
    name: '둔산 상권',
    region: '대전',
    district: '서구 둔산동',
    description: '대전 정부청사 + 학원가가 결합된 상권. 학생·공무원 객수가 안정적.',
    footTraffic: 38000,
    avgMonthlyRentPerPyeong: 11,
    avgRightFee: 2200,
    avgDeposit: 3200,
    topCategories: [
      { key: 'snack', label: '분식', share: 26 },
      { key: 'cafe', label: '카페', share: 22 },
      { key: 'beverage', label: '음료', share: 14 },
      { key: 'korean', label: '한식', share: 13 },
    ],
    highlights: ['학원가 + 청사 객수가 시간대별로 분산되어 회전율 좋음', '권리금이 광역 상권 중 가장 낮음'],
    cautions: ['겨울철 객수 감소', '방학 기간 매출 변동 큼'],
  },
]

export const LISTINGS: MockListing[] = [
  // ========= 서울 =========
  {
    id: 'l001',
    type: 'transfer',
    title: '강남역 도보 5분, 1층 코너 양도 매물',
    status: 'active',
    region: '서울',
    district: '강남구',
    fullAddress: '서울특별시 강남구 테헤란로 123 1층',
    areaKey: 'gangnam',
    area: 28,
    floor: '1층',
    buildingType: '상가',
    rightFee: 8500,
    deposit: 9000,
    monthlyRent: 580,
    fitCategories: ['cafe', 'korean', 'japanese', 'bar'],
    currentBusiness: '카페',
    monthlyRevenue: 3800,
    revenueVerified: true,
    tags: ['역세권', '코너', '1층', '대로변'],
    footTraffic: 9800,
    availableFrom: '2026-06-15',
    verified: true,
    featured: true,
    viewCount: 4820,
    inquiryCount: 38,
    createdAt: '2026-04-22',
    ownerType: 'agent',
    agencyName: '강남상권중개',
    imageColors: ['#10B981', '#34D399', '#6EE7B7'],
  },
  {
    id: 'l002',
    type: 'new',
    title: '신축 강남역 빌딩 2층 임대',
    status: 'active',
    region: '서울',
    district: '강남구',
    fullAddress: '서울특별시 강남구 강남대로 456 2층',
    areaKey: 'gangnam',
    area: 42,
    floor: '2층',
    buildingType: '상가',
    deposit: 12000,
    monthlyRent: 720,
    fitCategories: ['korean', 'japanese', 'bar'],
    tags: ['역세권', '신축', '엘리베이터', '주차 가능'],
    footTraffic: 9200,
    availableFrom: '2026-07-01',
    verified: true,
    featured: true,
    viewCount: 2940,
    inquiryCount: 22,
    createdAt: '2026-05-01',
    ownerType: 'direct',
    imageColors: ['#10B981', '#059669'],
  },
  {
    id: 'l003',
    type: 'transfer',
    title: '홍대 골목 카페 양도 (인테리어 양호)',
    status: 'active',
    region: '서울',
    district: '마포구',
    fullAddress: '서울특별시 마포구 와우산로 78',
    areaKey: 'hongdae',
    area: 12,
    floor: '1층',
    buildingType: '상가',
    rightFee: 2500,
    deposit: 4000,
    monthlyRent: 230,
    fitCategories: ['cafe', 'dessert', 'beverage'],
    currentBusiness: '카페',
    monthlyRevenue: 1850,
    revenueVerified: true,
    tags: ['SNS 상권', '인테리어 양호', '주거지 인근', '1층'],
    footTraffic: 3200,
    availableFrom: '2026-05-25',
    verified: true,
    featured: false,
    viewCount: 1820,
    inquiryCount: 14,
    createdAt: '2026-04-15',
    ownerType: 'direct',
    imageColors: ['#F59E0B', '#FBBF24'],
  },
  {
    id: 'l004',
    type: 'new',
    title: '홍대입구역 신축 상가 1층 (광장 면)',
    status: 'active',
    region: '서울',
    district: '마포구',
    fullAddress: '서울특별시 마포구 어울마당로 99',
    areaKey: 'hongdae',
    area: 32,
    floor: '1층',
    buildingType: '상가',
    deposit: 8500,
    monthlyRent: 520,
    fitCategories: ['cafe', 'snack', 'dessert', 'beverage', 'bar'],
    tags: ['역세권', '신축', '광장 면', '1층'],
    footTraffic: 8400,
    availableFrom: '2026-06-20',
    verified: true,
    featured: false,
    viewCount: 1640,
    inquiryCount: 11,
    createdAt: '2026-04-30',
    ownerType: 'agent',
    agencyName: '홍대상권부동산',
    imageColors: ['#3B82F6', '#60A5FA'],
  },
  {
    id: 'l005',
    type: 'transfer',
    title: '연남동 골목 디저트 카페 양도',
    status: 'active',
    region: '서울',
    district: '마포구',
    fullAddress: '서울특별시 마포구 동교로 41',
    areaKey: 'hongdae',
    area: 14,
    floor: '1층',
    buildingType: '상가',
    rightFee: 3200,
    deposit: 3500,
    monthlyRent: 210,
    fitCategories: ['dessert', 'cafe', 'beverage'],
    currentBusiness: '디저트 카페',
    monthlyRevenue: 1620,
    revenueVerified: false,
    tags: ['연남동', '인테리어 가능', '주거 인근'],
    footTraffic: 2200,
    availableFrom: '2026-05-30',
    verified: true,
    featured: false,
    viewCount: 980,
    inquiryCount: 7,
    createdAt: '2026-05-02',
    ownerType: 'direct',
    imageColors: ['#EC4899', '#F472B6'],
  },
  {
    id: 'l006',
    type: 'transfer',
    title: '여의도 오피스 빌딩 지하 1층 식당 양도',
    status: 'active',
    region: '서울',
    district: '영등포구',
    fullAddress: '서울특별시 영등포구 여의대로 24',
    area: 24,
    floor: '지하 1층',
    buildingType: '오피스 빌딩',
    rightFee: 3000,
    deposit: 5500,
    monthlyRent: 310,
    fitCategories: ['korean', 'japanese', 'snack', 'cafe'],
    currentBusiness: '한식 도시락',
    monthlyRevenue: 2280,
    revenueVerified: true,
    tags: ['오피스 상권', '지하 1층', '직장인 점심', '주방 설비'],
    footTraffic: 4400,
    availableFrom: '2026-05-25',
    verified: true,
    featured: false,
    viewCount: 1410,
    inquiryCount: 12,
    createdAt: '2026-04-28',
    ownerType: 'direct',
    imageColors: ['#64748B', '#94A3B8'],
  },
  {
    id: 'l007',
    type: 'sale',
    title: '서울 노원 상가 매각 (3층 단독)',
    status: 'active',
    region: '서울',
    district: '노원구',
    fullAddress: '서울특별시 노원구 동일로 1144',
    area: 86,
    floor: '1-3층',
    buildingType: '단독 상가',
    deposit: 0,
    monthlyRent: 0,
    salePrice: 380000,
    fitCategories: ['cafe', 'chicken', 'korean'],
    tags: ['단독 건물', '3층', '주차 6대', '주거지'],
    footTraffic: 5200,
    availableFrom: '2026-08-01',
    verified: true,
    featured: false,
    viewCount: 2150,
    inquiryCount: 18,
    createdAt: '2026-04-10',
    ownerType: 'direct',
    imageColors: ['#7C3AED', '#A78BFA'],
  },

  // ========= 경기/인천 =========
  {
    id: 'l008',
    type: 'new',
    title: '판교 IT 단지 1층 코너 신축 매물',
    status: 'active',
    region: '경기',
    district: '성남시 분당구',
    fullAddress: '경기도 성남시 분당구 판교역로 234',
    areaKey: 'pangyo',
    area: 14,
    floor: '1층',
    buildingType: '신축 상가',
    deposit: 5000,
    monthlyRent: 280,
    fitCategories: ['cafe', 'snack', 'korean'],
    tags: ['오피스 상권', '코너', '1층', '신축'],
    footTraffic: 4800,
    availableFrom: '2026-06-01',
    verified: true,
    featured: true,
    viewCount: 3120,
    inquiryCount: 27,
    createdAt: '2026-04-25',
    ownerType: 'agent',
    agencyName: '판교상권컨설팅',
    imageColors: ['#10B981', '#34D399'],
  },
  {
    id: 'l009',
    type: 'transfer',
    title: '인천 송도 신도시 코너 매물 양도',
    status: 'active',
    region: '인천',
    district: '연수구 송도동',
    fullAddress: '인천광역시 연수구 송도과학로 16',
    areaKey: 'songdo',
    area: 32,
    floor: '1층',
    buildingType: '상가',
    rightFee: 4200,
    deposit: 7000,
    monthlyRent: 420,
    fitCategories: ['chicken', 'korean', 'japanese', 'cafe'],
    currentBusiness: '치킨',
    monthlyRevenue: 2950,
    revenueVerified: true,
    tags: ['신도시', '코너', '대형 아파트 단지', '1층'],
    footTraffic: 5100,
    availableFrom: '2026-06-20',
    verified: true,
    featured: false,
    viewCount: 1890,
    inquiryCount: 16,
    createdAt: '2026-04-18',
    ownerType: 'direct',
    imageColors: ['#10B981', '#059669'],
  },
  {
    id: 'l010',
    type: 'new',
    title: '수원 영통구 신축 상가 임대',
    status: 'active',
    region: '경기',
    district: '수원시 영통구',
    fullAddress: '경기도 수원시 영통구 영통로 200',
    area: 22,
    floor: '1층',
    buildingType: '신축 상가',
    deposit: 4500,
    monthlyRent: 280,
    fitCategories: ['cafe', 'snack', 'dessert'],
    tags: ['신축', '대로변', '주거 단지'],
    footTraffic: 3800,
    availableFrom: '2026-06-10',
    verified: true,
    featured: false,
    viewCount: 1240,
    inquiryCount: 9,
    createdAt: '2026-04-29',
    ownerType: 'agent',
    agencyName: '수원상권공인',
    imageColors: ['#3B82F6', '#60A5FA'],
  },
  {
    id: 'l011',
    type: 'transfer',
    title: '안양 평촌 학원가 분식점 양도',
    status: 'active',
    region: '경기',
    district: '안양시 동안구',
    fullAddress: '경기도 안양시 동안구 평촌대로 67',
    area: 16,
    floor: '1층',
    buildingType: '상가',
    rightFee: 1800,
    deposit: 3000,
    monthlyRent: 180,
    fitCategories: ['snack', 'dessert', 'beverage'],
    currentBusiness: '분식',
    monthlyRevenue: 1520,
    revenueVerified: true,
    tags: ['학원가', '학생 상권', '1층'],
    footTraffic: 2800,
    availableFrom: '2026-06-15',
    verified: true,
    featured: false,
    viewCount: 1050,
    inquiryCount: 8,
    createdAt: '2026-04-21',
    ownerType: 'direct',
    imageColors: ['#F59E0B', '#FBBF24'],
  },

  // ========= 부산 =========
  {
    id: 'l012',
    type: 'transfer',
    title: '해운대 신축 상가 1층 양도',
    status: 'active',
    region: '부산',
    district: '해운대구',
    fullAddress: '부산광역시 해운대구 해운대로 567',
    area: 22,
    floor: '1층',
    buildingType: '신축 상가',
    rightFee: 0,
    deposit: 6000,
    monthlyRent: 380,
    fitCategories: ['cafe', 'dessert', 'beverage', 'snack'],
    tags: ['신축', '관광 상권', '1층'],
    footTraffic: 5600,
    availableFrom: '2026-07-01',
    verified: true,
    featured: true,
    viewCount: 2640,
    inquiryCount: 19,
    createdAt: '2026-04-12',
    ownerType: 'agent',
    agencyName: '해운대공인',
    imageColors: ['#06B6D4', '#22D3EE'],
  },
  {
    id: 'l013',
    type: 'transfer',
    title: '부산 서면 1.5층 매물 양도',
    status: 'active',
    region: '부산',
    district: '부산진구',
    fullAddress: '부산광역시 부산진구 중앙대로 668',
    areaKey: 'seomyeon',
    area: 26,
    floor: '1.5층',
    buildingType: '상가',
    rightFee: 5500,
    deposit: 6000,
    monthlyRent: 350,
    fitCategories: ['bar', 'korean', 'japanese'],
    currentBusiness: '주점',
    monthlyRevenue: 3450,
    revenueVerified: true,
    tags: ['상권 중심', '1.5층', '인테리어 가능'],
    footTraffic: 7400,
    availableFrom: '2026-06-01',
    verified: true,
    featured: false,
    viewCount: 2210,
    inquiryCount: 17,
    createdAt: '2026-04-20',
    ownerType: 'direct',
    imageColors: ['#7C3AED', '#A78BFA'],
  },
  {
    id: 'l014',
    type: 'new',
    title: '부산 광안리 해변 신축 1층',
    status: 'active',
    region: '부산',
    district: '수영구',
    fullAddress: '부산광역시 수영구 광안해변로 220',
    area: 38,
    floor: '1층',
    buildingType: '신축 상가',
    deposit: 8500,
    monthlyRent: 480,
    fitCategories: ['cafe', 'bar', 'dessert'],
    tags: ['해변', '관광 상권', '신축', '1층'],
    footTraffic: 8200,
    availableFrom: '2026-07-15',
    verified: true,
    featured: false,
    viewCount: 1830,
    inquiryCount: 13,
    createdAt: '2026-05-03',
    ownerType: 'agent',
    agencyName: '광안리부동산',
    imageColors: ['#0EA5E9', '#38BDF8'],
  },

  // ========= 기타 광역 =========
  {
    id: 'l015',
    type: 'transfer',
    title: '대구 동성로 코너 카페 양도',
    status: 'active',
    region: '대구',
    district: '중구',
    fullAddress: '대구광역시 중구 동성로 134',
    areaKey: 'dongseongro',
    area: 18,
    floor: '1층',
    buildingType: '상가',
    rightFee: 3200,
    deposit: 4200,
    monthlyRent: 260,
    fitCategories: ['cafe', 'dessert', 'beverage'],
    currentBusiness: '카페',
    monthlyRevenue: 1820,
    revenueVerified: false,
    tags: ['상권 중심', '코너', '1층'],
    footTraffic: 6200,
    availableFrom: '2026-06-10',
    verified: true,
    featured: false,
    viewCount: 1340,
    inquiryCount: 11,
    createdAt: '2026-04-26',
    ownerType: 'agent',
    agencyName: '동성로상권',
    imageColors: ['#A16207', '#CA8A04'],
  },
  {
    id: 'l016',
    type: 'new',
    title: '대구 수성구 신축 상가 1층',
    status: 'active',
    region: '대구',
    district: '수성구',
    fullAddress: '대구광역시 수성구 동대구로 380',
    area: 24,
    floor: '1층',
    buildingType: '신축 상가',
    deposit: 4800,
    monthlyRent: 240,
    fitCategories: ['cafe', 'snack', 'korean'],
    tags: ['신축', '학원가 인근', '주거 단지'],
    footTraffic: 3400,
    availableFrom: '2026-06-25',
    verified: true,
    featured: false,
    viewCount: 920,
    inquiryCount: 6,
    createdAt: '2026-05-04',
    ownerType: 'direct',
    imageColors: ['#16A34A', '#22C55E'],
  },
  {
    id: 'l017',
    type: 'transfer',
    title: '대전 둔산 학원가 분식 양도',
    status: 'active',
    region: '대전',
    district: '서구 둔산동',
    fullAddress: '대전광역시 서구 둔산로 92',
    areaKey: 'dunsan',
    area: 16,
    floor: '1층',
    buildingType: '상가',
    rightFee: 1800,
    deposit: 3500,
    monthlyRent: 180,
    fitCategories: ['snack', 'dessert', 'beverage', 'cafe'],
    currentBusiness: '분식',
    monthlyRevenue: 1480,
    revenueVerified: true,
    tags: ['학원가', '학생 상권', '인테리어 양호'],
    footTraffic: 2800,
    availableFrom: '2026-06-05',
    verified: true,
    featured: false,
    viewCount: 1120,
    inquiryCount: 9,
    createdAt: '2026-04-24',
    ownerType: 'agent',
    agencyName: '둔산상권공인',
    imageColors: ['#DC2626', '#EF4444'],
  },
  {
    id: 'l018',
    type: 'new',
    title: '광주 충장로 신축 매물',
    status: 'active',
    region: '광주',
    district: '동구 충장로',
    fullAddress: '광주광역시 동구 충장로 88',
    areaKey: 'chungjangro',
    area: 28,
    floor: '1층',
    buildingType: '신축 상가',
    deposit: 5500,
    monthlyRent: 280,
    fitCategories: ['cafe', 'snack', 'korean', 'dessert'],
    tags: ['상권 중심', '신축', '1층'],
    footTraffic: 4400,
    availableFrom: '2026-07-05',
    verified: true,
    featured: false,
    viewCount: 880,
    inquiryCount: 5,
    createdAt: '2026-05-05',
    ownerType: 'direct',
    imageColors: ['#0EA5E9', '#38BDF8'],
  },
  {
    id: 'l019',
    type: 'transfer',
    title: '울산 삼산동 치킨 매장 양도',
    status: 'active',
    region: '울산',
    district: '남구 삼산동',
    fullAddress: '울산광역시 남구 삼산로 240',
    area: 30,
    floor: '1층',
    buildingType: '상가',
    rightFee: 3500,
    deposit: 6500,
    monthlyRent: 360,
    fitCategories: ['chicken', 'korean', 'snack', 'bar'],
    currentBusiness: '치킨',
    monthlyRevenue: 2820,
    revenueVerified: true,
    tags: ['상권 중심', '주차 가능', '주방 설비'],
    footTraffic: 4200,
    availableFrom: '2026-07-15',
    verified: true,
    featured: false,
    viewCount: 760,
    inquiryCount: 6,
    createdAt: '2026-04-19',
    ownerType: 'agent',
    agencyName: '울산상권부동산',
    imageColors: ['#EA580C', '#F97316'],
  },
  {
    id: 'l020',
    type: 'sale',
    title: '제주 함덕 상가 매각',
    status: 'active',
    region: '제주',
    district: '제주시 조천읍 함덕리',
    fullAddress: '제주특별자치도 제주시 조천읍 함덕로 1234',
    area: 64,
    floor: '1-2층',
    buildingType: '상가 (양옆 노출)',
    deposit: 0,
    monthlyRent: 0,
    salePrice: 280000,
    fitCategories: ['cafe', 'korean'],
    tags: ['해변 인근', '관광 상권', '2개층'],
    footTraffic: 4800,
    availableFrom: '2026-09-01',
    verified: true,
    featured: false,
    viewCount: 1620,
    inquiryCount: 12,
    createdAt: '2026-04-08',
    ownerType: 'direct',
    imageColors: ['#0EA5E9', '#06B6D4'],
  },
  {
    id: 'l021',
    type: 'new',
    title: '서울 영등포 오피스 빌딩 1층 임대',
    status: 'active',
    region: '서울',
    district: '영등포구',
    fullAddress: '서울특별시 영등포구 국제금융로 25',
    area: 38,
    floor: '1층',
    buildingType: '오피스 빌딩',
    deposit: 9500,
    monthlyRent: 550,
    fitCategories: ['cafe', 'korean', 'japanese'],
    tags: ['오피스 상권', '대로변', '1층'],
    footTraffic: 6800,
    availableFrom: '2026-08-01',
    verified: true,
    featured: false,
    viewCount: 1450,
    inquiryCount: 10,
    createdAt: '2026-04-30',
    ownerType: 'agent',
    agencyName: '여의도공인',
    imageColors: ['#475569', '#64748B'],
  },
  {
    id: 'l022',
    type: 'transfer',
    title: '강동구 천호동 한식당 양도',
    status: 'active',
    region: '서울',
    district: '강동구',
    fullAddress: '서울특별시 강동구 천호대로 1095',
    area: 36,
    floor: '1층',
    buildingType: '상가',
    rightFee: 4500,
    deposit: 5500,
    monthlyRent: 320,
    fitCategories: ['korean', 'japanese', 'snack'],
    currentBusiness: '한식당',
    monthlyRevenue: 2640,
    revenueVerified: true,
    tags: ['주거 인근', '주차 가능', '주방 설비'],
    footTraffic: 4100,
    availableFrom: '2026-06-25',
    verified: true,
    featured: false,
    viewCount: 1180,
    inquiryCount: 8,
    createdAt: '2026-04-27',
    ownerType: 'direct',
    imageColors: ['#16A34A', '#22C55E'],
  },
  {
    id: 'l023',
    type: 'new',
    title: '인천 부평구 신축 상가 1층',
    status: 'active',
    region: '인천',
    district: '부평구',
    fullAddress: '인천광역시 부평구 부평대로 78',
    area: 26,
    floor: '1층',
    buildingType: '신축 상가',
    deposit: 5200,
    monthlyRent: 290,
    fitCategories: ['cafe', 'snack', 'korean', 'chicken'],
    tags: ['역세권', '신축', '1층'],
    footTraffic: 4400,
    availableFrom: '2026-07-10',
    verified: true,
    featured: false,
    viewCount: 1080,
    inquiryCount: 7,
    createdAt: '2026-05-06',
    ownerType: 'agent',
    agencyName: '부평상권공인',
    imageColors: ['#10B981', '#059669'],
  },
  {
    id: 'l024',
    type: 'transfer',
    title: '서울 종로 한정식 매물 양도',
    status: 'active',
    region: '서울',
    district: '종로구',
    fullAddress: '서울특별시 종로구 종로 124',
    area: 44,
    floor: '1-2층',
    buildingType: '상가',
    rightFee: 6500,
    deposit: 7500,
    monthlyRent: 450,
    fitCategories: ['korean', 'bar'],
    currentBusiness: '한정식',
    monthlyRevenue: 3650,
    revenueVerified: true,
    tags: ['관광 상권', '2개층', '주방 설비'],
    footTraffic: 5800,
    availableFrom: '2026-07-01',
    verified: true,
    featured: false,
    viewCount: 1340,
    inquiryCount: 9,
    createdAt: '2026-04-23',
    ownerType: 'direct',
    imageColors: ['#A16207', '#CA8A04'],
  },
  {
    id: 'l025',
    type: 'sale',
    title: '경기 일산 상가 매각 (1층 카페 운영중)',
    status: 'active',
    region: '경기',
    district: '고양시 일산동구',
    fullAddress: '경기도 고양시 일산동구 정발산로 25',
    area: 38,
    floor: '1층',
    buildingType: '상가',
    deposit: 0,
    monthlyRent: 0,
    salePrice: 210000,
    fitCategories: ['cafe', 'snack', 'dessert'],
    tags: ['주거 단지', '카페 운영 중', '1층'],
    footTraffic: 3600,
    availableFrom: '2026-08-15',
    verified: true,
    featured: false,
    viewCount: 1490,
    inquiryCount: 11,
    createdAt: '2026-04-16',
    ownerType: 'agent',
    agencyName: '일산상권부동산',
    imageColors: ['#7C3AED', '#A78BFA'],
  },
]

export const FEATURED_LISTINGS = LISTINGS.filter((l) => l.featured)
export const TRANSFER_LISTINGS = LISTINGS.filter((l) => l.type === 'transfer')
export const NEW_LISTINGS = LISTINGS.filter((l) => l.type === 'new')
export const SALE_LISTINGS = LISTINGS.filter((l) => l.type === 'sale')

/** Top-N popular listings by view count. */
export function popularListings(limit = 6): MockListing[] {
  return [...LISTINGS].sort((a, b) => b.viewCount - a.viewCount).slice(0, limit)
}

export function listingsByArea(areaKey: string): MockListing[] {
  return LISTINGS.filter((l) => l.areaKey === areaKey)
}
