// Mock data for themyungdang (real-estate for franchise spaces).
// Mirrors the shape we'd get from the Listings table once Supabase is live.

import { listingPhotoSet } from './listing-images'
import cmRaw from './cm-listings.json'

export type ListingType = 'transfer' | 'new' | 'sale'

export interface MockListing {
  id: string
  type: ListingType
  title: string
  status: 'active' | 'pending' | 'completed'
  region: string
  district: string
  fullAddress: string
  areaKey?: string
  area: number // 평
  floor: string
  buildingType: string
  rightFee?: number
  deposit: number
  monthlyRent: number
  salePrice?: number
  fitCategories: string[]
  currentBusiness?: string
  monthlyRevenue?: number
  revenueVerified?: boolean
  tags: string[]
  footTraffic: number
  availableFrom: string
  verified: boolean
  featured: boolean
  viewCount: number
  inquiryCount: number
  createdAt: string
  ownerType: 'direct' | 'agent'
  agencyName?: string
  /** Fallback gradient colors (kept for backwards compat). */
  imageColors: string[]
  /** Real photos (hero + interior shots). Filled automatically below. */
  images: string[]
  /** Owner / agent's pitch shown on detail page. */
  transferorMessage?: string
  /** WGS84 좌표 — 지도 핀 표시용. 없으면 지도에서 제외. */
  lat?: number
  lng?: number
  /** 등록자/중개사 연락처 (표시용). 없으면 대표 번호로 폴백. */
  contactPhone?: string
  /** 외부 사이트에서 수집한 매물의 출처 정보. 자체 등록(직거래·중개)이면 비움.
   *  추후 changupmall·점포라인·점포거래소 등 여러 출처를 동일 LISTINGS 배열에 합칠 수 있도록 마련. */
  externalSource?: {
    name: string       // 'changupmall' 등 슬러그
    label: string      // '창업몰' 등 사용자 노출용 이름
    sourceId: string   // 원본 사이트의 매물 ID
    url: string        // 원본 상세 URL (참조용, 직접 노출은 정책에 따라)
    fetchedAt: string  // ISO 날짜
  }
}

export interface MockArea {
  key: string
  name: string
  region: string
  district: string
  description: string
  /** 일 평균 유동인구 (명) */
  footTraffic: number
  /** 평당 평균 월세 (만원) */
  avgMonthlyRentPerPyeong: number
  /** 평균 권리금 (만원) */
  avgRightFee: number
  /** 평균 보증금 (만원) */
  avgDeposit: number
  /** 주요 업종 비중 */
  topCategories: Array<{ key: string; label: string; share: number }>
  highlights: string[]
  cautions: string[]
  /** 상권 중심 좌표 — 지도 오버레이 원 표시용 */
  lat?: number
  lng?: number
  /** 오버레이 반경 (미터) */
  radiusM?: number
}

export interface ListingCategory {
  key: string
  label: string
  brandRefCount: number
}

export const LISTING_CATEGORIES: ListingCategory[] = [
  { key: 'chicken', label: '치킨', brandRefCount: 142 },
  { key: 'cafe', label: '카페', brandRefCount: 318 },
  { key: 'korean', label: '한식', brandRefCount: 87 },
  { key: 'japanese', label: '일식', brandRefCount: 54 },
  { key: 'snack', label: '분식', brandRefCount: 76 },
  { key: 'dessert', label: '디저트', brandRefCount: 49 },
  { key: 'beverage', label: '음료', brandRefCount: 62 },
  { key: 'bar', label: '주점', brandRefCount: 38 },
  { key: 'convenience', label: '편의점', brandRefCount: 24 },
  { key: 'education', label: '교육', brandRefCount: 41 },
]

export const TYPE_LABEL: Record<ListingType, string> = {
  transfer: '양도',
  new: '신규 임대',
  sale: '매각',
}

export const AREAS: MockArea[] = [
  {
    key: 'gangnam',
    name: '강남역 상권',
    region: '서울',
    district: '강남구',
    description:
      '국내 최상위 사무 + 유흥 복합 상권. 객단가가 높고 회전율이 좋지만 임대료 부담도 가장 큽니다.',
    footTraffic: 92000,
    avgMonthlyRentPerPyeong: 22,
    avgRightFee: 8500,
    avgDeposit: 9000,
    topCategories: [
      { key: 'cafe', label: '카페', share: 28 },
      { key: 'korean', label: '한식', share: 18 },
      { key: 'bar', label: '주점', share: 16 },
      { key: 'japanese', label: '일식', share: 12 },
    ],
    highlights: [
      '오피스 점심 + 저녁 + 심야까지 객수가 끊기지 않음',
      '대형 브랜드와 신규 브랜드가 공존하는 트렌드 시험장',
    ],
    cautions: [
      '평당 월세가 다른 상권의 2-3배. 매출이 평균 이상이어도 손익이 빠듯할 수 있음',
      '공시 매물보다 부동산 직접 협상으로 거래되는 비율이 높아 정보 비대칭이 큼',
    ],
    lat: 37.4981, lng: 127.0276, radiusM: 600,
  },
  {
    key: 'hongdae',
    name: '홍대 상권',
    region: '서울',
    district: '마포구',
    description:
      'SNS·트렌드 매장이 집중되는 20-30대 상권. 디저트·카페·캐주얼 다이닝 매장이 강세입니다.',
    footTraffic: 74000,
    avgMonthlyRentPerPyeong: 18,
    avgRightFee: 5500,
    avgDeposit: 6500,
    topCategories: [
      { key: 'cafe', label: '카페', share: 32 },
      { key: 'dessert', label: '디저트', share: 18 },
      { key: 'snack', label: '분식', share: 15 },
      { key: 'bar', label: '주점', share: 14 },
    ],
    highlights: ['SNS 노출 효과가 큰 입지', '관광객 비중 25% 이상으로 평일·주말 매출 차이가 작음'],
    cautions: ['매물 교체 주기가 빠릅니다 — 평균 보증금 회수 기간 2.8년', '소음·민원 발생 빈도가 높음'],
    lat: 37.5571, lng: 126.9240, radiusM: 500,
  },
  {
    key: 'pangyo',
    name: '판교 IT 단지',
    region: '경기',
    district: '성남시 분당구',
    description:
      '국내 대형 IT 본사 밀집 지역. 평일 점심·저녁 객수가 안정적이지만 주말 매출은 약한 편.',
    footTraffic: 48000,
    avgMonthlyRentPerPyeong: 16,
    avgRightFee: 4500,
    avgDeposit: 5500,
    topCategories: [
      { key: 'cafe', label: '카페', share: 30 },
      { key: 'korean', label: '한식', share: 22 },
      { key: 'snack', label: '분식', share: 12 },
      { key: 'japanese', label: '일식', share: 11 },
    ],
    highlights: ['평일 점심 객수가 매우 안정적', '신축 상가 비율이 높아 시설 컨디션 좋음'],
    cautions: ['주말 매출이 평일의 50% 수준 — 평일 매출로 손익 맞춰야 함', '대기업 구내식당 경쟁'],
    lat: 37.3952, lng: 127.1116, radiusM: 700,
  },
  {
    key: 'songdo',
    name: '송도 신도시',
    region: '인천',
    district: '연수구 송도동',
    description:
      '아파트 단지 + 신축 상가 + 외국인 거주 비중이 높은 신도시 상권. 가족 단위 객수 강세.',
    footTraffic: 32000,
    avgMonthlyRentPerPyeong: 13,
    avgRightFee: 2800,
    avgDeposit: 4200,
    topCategories: [
      { key: 'cafe', label: '카페', share: 26 },
      { key: 'korean', label: '한식', share: 20 },
      { key: 'snack', label: '분식', share: 14 },
      { key: 'chicken', label: '치킨', share: 13 },
    ],
    highlights: ['신축 상가라 시설 추가 비용이 적음', '주거 + 직장 + 외국인 객수 균형'],
    cautions: ['평일 점심 의존도가 낮은 만큼 회전 시간이 길어짐', '신도시 특성상 상권 안정화에 1-2년'],
    lat: 37.3944, lng: 126.6528, radiusM: 800,
  },
  {
    key: 'seomyeon',
    name: '서면 상권',
    region: '부산',
    district: '부산진구',
    description: '부산 중심 상권. 1·2층 노출 좋은 매물이 인기가 많고 저녁 매출 비중이 큼.',
    footTraffic: 65000,
    avgMonthlyRentPerPyeong: 15,
    avgRightFee: 4200,
    avgDeposit: 5500,
    topCategories: [
      { key: 'bar', label: '주점', share: 24 },
      { key: 'korean', label: '한식', share: 22 },
      { key: 'cafe', label: '카페', share: 16 },
      { key: 'japanese', label: '일식', share: 13 },
    ],
    highlights: ['관광 + 현지 객수가 균형', '저녁 + 심야 객수 강세로 주점·다이닝에 유리'],
    cautions: ['주말 매출 의존도 + 시즌 변동성 큼', '인접 상권과 경쟁이 치열'],
    lat: 35.1572, lng: 129.0593, radiusM: 500,
  },
  {
    key: 'dongseongro',
    name: '동성로 상권',
    region: '대구',
    district: '중구',
    description: '대구 최대 상권. 10대-20대 객수가 많고 패션·F&B가 함께 자리잡은 곳.',
    footTraffic: 58000,
    avgMonthlyRentPerPyeong: 14,
    avgRightFee: 3800,
    avgDeposit: 5000,
    topCategories: [
      { key: 'snack', label: '분식', share: 22 },
      { key: 'cafe', label: '카페', share: 20 },
      { key: 'bar', label: '주점', share: 15 },
      { key: 'dessert', label: '디저트', share: 12 },
    ],
    highlights: ['학생 + 직장인 객수의 균형', '대구 외 지역에서도 방문하는 광역 상권'],
    cautions: ['10-20대 객수가 많아 객단가 한계가 있음', '폐점율은 평균보다 다소 높음'],
    lat: 35.8684, lng: 128.5968, radiusM: 400,
  },
  {
    key: 'chungjangro',
    name: '충장로 상권',
    region: '광주',
    district: '동구',
    description: '광주 핵심 상권. 권리금·임대료가 광주 내 가장 높지만 객수 안정성도 가장 높음.',
    footTraffic: 42000,
    avgMonthlyRentPerPyeong: 12,
    avgRightFee: 2800,
    avgDeposit: 3800,
    topCategories: [
      { key: 'cafe', label: '카페', share: 28 },
      { key: 'snack', label: '분식', share: 18 },
      { key: 'korean', label: '한식', share: 16 },
      { key: 'dessert', label: '디저트', share: 12 },
    ],
    highlights: ['광주광역시 객수의 30% 이상이 집중', '주말·평일 객수 균형이 좋음'],
    cautions: ['신축 상가가 적어 시설 보강 비용 필요', '권리금 평균이 빠르게 상승 중'],
    lat: 35.1523, lng: 126.9162, radiusM: 350,
  },
  {
    key: 'dunsan',
    name: '둔산 상권',
    region: '대전',
    district: '서구 둔산동',
    description: '대전 정부청사 + 학원가가 결합된 상권. 학생·공무원 객수가 안정적.',
    footTraffic: 38000,
    avgMonthlyRentPerPyeong: 11,
    avgRightFee: 2200,
    avgDeposit: 3200,
    topCategories: [
      { key: 'snack', label: '분식', share: 26 },
      { key: 'cafe', label: '카페', share: 22 },
      { key: 'beverage', label: '음료', share: 14 },
      { key: 'korean', label: '한식', share: 13 },
    ],
    highlights: ['학원가 + 청사 객수가 시간대별로 분산되어 회전율 좋음', '권리금이 광역 상권 중 가장 낮음'],
    cautions: ['겨울철 객수 감소', '방학 기간 매출 변동 큼'],
    lat: 36.3504, lng: 127.3846, radiusM: 500,
  },
  // ── 추가 12개 상권 ─────────────────────────────────────────────────────────
  {
    key: 'sinchon',
    name: '신촌 상권',
    region: '서울',
    district: '서대문구',
    description: '연세·이화·홍익대 인근 대학가 상권. 저녁·심야 매출 비중이 높고 방학 시즌 영향이 큽니다.',
    footTraffic: 62000,
    avgMonthlyRentPerPyeong: 16,
    avgRightFee: 4600,
    avgDeposit: 5800,
    topCategories: [
      { key: 'bar', label: '주점', share: 26 },
      { key: 'cafe', label: '카페', share: 22 },
      { key: 'snack', label: '분식', share: 16 },
      { key: 'beverage', label: '음료', share: 11 },
    ],
    highlights: ['대학생 고정 객수', '심야 2-3시까지 매출 발생'],
    cautions: ['방학 6주 동안 매출 40% 이상 감소', '홍대 상권에 젊은층 일부 이탈'],
    lat: 37.5547, lng: 126.9376, radiusM: 420,
  },
  {
    key: 'itaewon',
    name: '이태원 상권',
    region: '서울',
    district: '용산구',
    description: '외국인·관광객 비중이 높은 글로벌 상권. 이색 F&B와 바(Bar)에 강하며 이국적 콘셉트에 유리.',
    footTraffic: 51000,
    avgMonthlyRentPerPyeong: 17,
    avgRightFee: 5200,
    avgDeposit: 6000,
    topCategories: [
      { key: 'bar', label: '주점', share: 30 },
      { key: 'cafe', label: '카페', share: 18 },
      { key: 'korean', label: '한식', share: 14 },
      { key: 'japanese', label: '일식', share: 12 },
    ],
    highlights: ['외국인 객수 30% 이상 — 높은 객단가', '심야 매출 강세'],
    cautions: ['상권 등락이 크고 폐점 후 재임대 기간이 길 수 있음', '평일 낮 매출 낮음'],
    lat: 37.5345, lng: 126.9947, radiusM: 450,
  },
  {
    key: 'konkuk',
    name: '건대입구 상권',
    region: '서울',
    district: '광진구',
    description: '건국대·세종대 연계 학생 상권이지만 직장인 저녁 수요도 강합니다. 야간 매출 비중 60% 이상.',
    footTraffic: 67000,
    avgMonthlyRentPerPyeong: 16,
    avgRightFee: 4800,
    avgDeposit: 5500,
    topCategories: [
      { key: 'bar', label: '주점', share: 28 },
      { key: 'snack', label: '분식', share: 20 },
      { key: 'cafe', label: '카페', share: 18 },
      { key: 'chicken', label: '치킨', share: 14 },
    ],
    highlights: ['야간 매출 비중 업계 최고 수준', '먹자골목 집객 효과'],
    cautions: ['낮 시간 매출 비중 낮아 운영 시간 길어짐', '방학 시즌 변동'],
    lat: 37.5401, lng: 127.0701, radiusM: 400,
  },
  {
    key: 'jamsil',
    name: '잠실 상권',
    region: '서울',
    district: '송파구',
    description: '대규모 아파트 단지 + 롯데월드·스포츠 컴플렉스가 인접한 복합 상권. 주말 대규모 집객.',
    footTraffic: 78000,
    avgMonthlyRentPerPyeong: 19,
    avgRightFee: 6200,
    avgDeposit: 7800,
    topCategories: [
      { key: 'cafe', label: '카페', share: 24 },
      { key: 'korean', label: '한식', share: 20 },
      { key: 'dessert', label: '디저트', share: 16 },
      { key: 'snack', label: '분식', share: 12 },
    ],
    highlights: ['주말 이벤트 시즌 매출 급등', '가족 단위 객수로 객단가 안정'],
    cautions: ['대형 쇼핑몰 푸드코트와 직접 경쟁', '임대료 상승 가파름'],
    lat: 37.5133, lng: 127.1001, radiusM: 600,
  },
  {
    key: 'myeongdong',
    name: '명동 상권',
    region: '서울',
    district: '중구',
    description: '외국인 관광객 비중 40% 이상의 관광 특화 상권. 코스메틱·디저트·한식 중심.',
    footTraffic: 88000,
    avgMonthlyRentPerPyeong: 21,
    avgRightFee: 7800,
    avgDeposit: 8500,
    topCategories: [
      { key: 'dessert', label: '디저트', share: 28 },
      { key: 'snack', label: '분식', share: 22 },
      { key: 'cafe', label: '카페', share: 20 },
      { key: 'korean', label: '한식', share: 15 },
    ],
    highlights: ['해외 관광객 집중 — 환율 호황 시 매출 급등', '글로벌 브랜드 신규 진입 테스트 베드'],
    cautions: ['관광객 감소 시 매출 타격 크고 내국인 방문 비중 낮음', '임대료 최상위권'],
    lat: 37.5636, lng: 126.9845, radiusM: 500,
  },
  {
    key: 'seongsu',
    name: '성수동 상권',
    region: '서울',
    district: '성동구',
    description: 'MZ세대 팝업·독립 카페·프리미엄 F&B의 성지. 인스타 노출 효과와 브랜딩 가치가 높습니다.',
    footTraffic: 45000,
    avgMonthlyRentPerPyeong: 17,
    avgRightFee: 5800,
    avgDeposit: 6500,
    topCategories: [
      { key: 'cafe', label: '카페', share: 36 },
      { key: 'dessert', label: '디저트', share: 22 },
      { key: 'beverage', label: '음료', share: 16 },
      { key: 'korean', label: '한식', share: 10 },
    ],
    highlights: ['SNS 바이럴 효과로 오픈 초기 매출이 높음', '팝업 스토어 성지 — 브랜드 노출 기회'],
    cautions: ['임시 팝업 매장 경쟁으로 고정 매출 유지 어려움', '빠른 트렌드 변화'],
    lat: 37.5443, lng: 127.0561, radiusM: 500,
  },
  {
    key: 'haeundae',
    name: '해운대 상권',
    region: '부산',
    district: '해운대구',
    description: '해수욕장 + 마린시티 고급 주거가 결합된 관광·프리미엄 복합 상권. 여름 성수기 매출이 집중됩니다.',
    footTraffic: 72000,
    avgMonthlyRentPerPyeong: 18,
    avgRightFee: 5600,
    avgDeposit: 6800,
    topCategories: [
      { key: 'cafe', label: '카페', share: 30 },
      { key: 'bar', label: '주점', share: 22 },
      { key: 'korean', label: '한식', share: 18 },
      { key: 'japanese', label: '일식', share: 12 },
    ],
    highlights: ['여름 성수기 월매출 평시 대비 2-3배', '관광객 + 고소득 거주자 혼재'],
    cautions: ['비수기(11-3월) 매출 급감', '관광 상권 특성상 상권 가치 변동성'],
    lat: 35.1631, lng: 129.1636, radiusM: 600,
  },
  {
    key: 'suwon_ingye',
    name: '수원 인계동',
    region: '경기',
    district: '수원시 팔달구',
    description: '수원 최대 유흥·외식 상권. 직장인·대학생이 공존하는 안정적 저녁 상권.',
    footTraffic: 44000,
    avgMonthlyRentPerPyeong: 12,
    avgRightFee: 3200,
    avgDeposit: 4500,
    topCategories: [
      { key: 'bar', label: '주점', share: 26 },
      { key: 'korean', label: '한식', share: 22 },
      { key: 'cafe', label: '카페', share: 16 },
      { key: 'snack', label: '분식', share: 12 },
    ],
    highlights: ['수원 내 가장 높은 야간 집객', '경기도권 대도시 중 권리금 합리적'],
    cautions: ['주간 매출 약함 — 저녁 의존도 높음', '광교신도시에 일부 이탈'],
    lat: 37.2620, lng: 127.0274, radiusM: 500,
  },
  {
    key: 'jeonju_gaeksa',
    name: '전주 객사 상권',
    region: '전북',
    district: '전주시 완산구',
    description: '전주 한옥마을 인근의 관광·전통 상권. 한식·디저트 특화 매장에 유리하며 SNS 유입이 큽니다.',
    footTraffic: 36000,
    avgMonthlyRentPerPyeong: 10,
    avgRightFee: 2000,
    avgDeposit: 3000,
    topCategories: [
      { key: 'korean', label: '한식', share: 34 },
      { key: 'dessert', label: '디저트', share: 22 },
      { key: 'cafe', label: '카페', share: 18 },
      { key: 'snack', label: '분식', share: 12 },
    ],
    highlights: ['전통 인지도 + SNS 관광 트래픽', '임대료·권리금이 전국 최저 수준'],
    cautions: ['관광 시즌(봄·가을)에 집중 — 겨울 비수기 주의', '신규 브랜드보다 전통 콘셉트 강세'],
    lat: 35.8224, lng: 127.1489, radiusM: 380,
  },
  {
    key: 'ulsan_samsan',
    name: '울산 삼산 상권',
    region: '울산',
    district: '남구 삼산동',
    description: '현대차·조선업 직장인 중심의 안정적 상권. 저녁 외식·회식 수요가 꾸준합니다.',
    footTraffic: 41000,
    avgMonthlyRentPerPyeong: 11,
    avgRightFee: 2600,
    avgDeposit: 3800,
    topCategories: [
      { key: 'korean', label: '한식', share: 28 },
      { key: 'bar', label: '주점', share: 24 },
      { key: 'japanese', label: '일식', share: 16 },
      { key: 'cafe', label: '카페', share: 12 },
    ],
    highlights: ['대기업 직장인 고정 객수 — 경기 변동 영향 적음', '회식 수요로 대형 테이블 매장에 유리'],
    cautions: ['조선업 경기 하락 시 타격 가능', '주말 매출 평일 대비 낮음'],
    lat: 35.5381, lng: 129.3114, radiusM: 480,
  },
  {
    key: 'jeju_yeon',
    name: '제주 연동 상권',
    region: '제주',
    district: '제주시 연동',
    description: '제주시 최대 상권. 관광객·이주민·현지인이 고루 섞인 다층 구조. 카페·디저트 창업 수요 1위.',
    footTraffic: 39000,
    avgMonthlyRentPerPyeong: 14,
    avgRightFee: 3400,
    avgDeposit: 4500,
    topCategories: [
      { key: 'cafe', label: '카페', share: 34 },
      { key: 'dessert', label: '디저트', share: 20 },
      { key: 'beverage', label: '음료', share: 15 },
      { key: 'korean', label: '한식', share: 14 },
    ],
    highlights: ['관광+이주 수요로 연중 안정적 매출', '카페·디저트 브랜드 인지도 쌓기 최적'],
    cautions: ['성수기·비수기 매출 격차 크고 인건비 높음', '임대료 상승 속도 빠름'],
    lat: 33.4890, lng: 126.4983, radiusM: 450,
  },
  {
    key: 'daejeon_eunhaengdong',
    name: '대전 은행동',
    region: '대전',
    district: '중구 은행동',
    description: '대전 원도심 상권. 직장인·학생이 혼재하며 점심·저녁 매출이 고루 발생합니다.',
    footTraffic: 43000,
    avgMonthlyRentPerPyeong: 10,
    avgRightFee: 2400,
    avgDeposit: 3400,
    topCategories: [
      { key: 'korean', label: '한식', share: 26 },
      { key: 'cafe', label: '카페', share: 22 },
      { key: 'snack', label: '분식', share: 16 },
      { key: 'bar', label: '주점', share: 14 },
    ],
    highlights: ['점심·저녁 매출 균형이 좋아 단기 손익 맞추기 용이', '권리금·임대료 부담 낮음'],
    cautions: ['상권 성장이 정체 — 신규 트렌드 흡수가 늦음', '둔산 상권 대비 젊은 객수 약함'],
    lat: 36.3278, lng: 127.4276, radiusM: 360,
  },
]

type RawListing = Omit<MockListing, 'images'>

const RAW_LISTINGS: RawListing[] = [
  // ========= 서울 =========
  {
    id: 'l001',
    type: 'transfer',
    title: '강남역 도보 5분, 1층 코너 양도 매물',
    status: 'active',
    region: '서울',
    district: '강남구',
    fullAddress: '서울특별시 강남구 테헤란로 123 1층',
    areaKey: 'gangnam',
    area: 28,
    floor: '1층',
    buildingType: '상가',
    rightFee: 8500,
    deposit: 9000,
    monthlyRent: 580,
    fitCategories: ['cafe', 'korean', 'japanese', 'bar'],
    currentBusiness: '카페',
    monthlyRevenue: 3800,
    revenueVerified: true,
    tags: ['역세권', '코너', '1층', '대로변'],
    footTraffic: 9800,
    availableFrom: '2026-06-15',
    verified: true,
    featured: true,
    viewCount: 4820,
    inquiryCount: 38,
    createdAt: '2026-04-22',
    ownerType: 'agent',
    agencyName: '강남상권중개',
    contactPhone: '02-559-3721',
    transferorMessage: '4년간 운영한 카페로 단골 고객 비중이 40% 이상입니다. 매출 장부 및 원산지 증빙 전부 공개 가능합니다. 인수 후 첫 1개월 운영 동행도 협의 가능합니다.',
    imageColors: ['#10B981', '#34D399', '#6EE7B7'],
    lat: 37.4979,
    lng: 127.0276,
  },
  {
    id: 'l002',
    type: 'new',
    title: '신축 강남역 빌딩 2층 임대',
    status: 'active',
    region: '서울',
    district: '강남구',
    fullAddress: '서울특별시 강남구 강남대로 456 2층',
    areaKey: 'gangnam',
    area: 42,
    floor: '2층',
    buildingType: '상가',
    deposit: 12000,
    monthlyRent: 720,
    fitCategories: ['korean', 'japanese', 'bar'],
    tags: ['역세권', '신축', '엘리베이터', '주차 가능'],
    footTraffic: 9200,
    availableFrom: '2026-07-01',
    verified: true,
    featured: true,
    viewCount: 2940,
    inquiryCount: 22,
    createdAt: '2026-05-01',
    ownerType: 'direct',
    contactPhone: '010-8821-4590',
    imageColors: ['#10B981', '#059669'],
    lat: 37.4981,
    lng: 127.0286,
  },
  {
    id: 'l003',
    type: 'transfer',
    title: '홍대 골목 카페 양도 (인테리어 양호)',
    status: 'active',
    region: '서울',
    district: '마포구',
    fullAddress: '서울특별시 마포구 와우산로 78',
    areaKey: 'hongdae',
    area: 12,
    floor: '1층',
    buildingType: '상가',
    rightFee: 2500,
    deposit: 4000,
    monthlyRent: 230,
    fitCategories: ['cafe', 'dessert', 'beverage'],
    currentBusiness: '카페',
    monthlyRevenue: 1850,
    revenueVerified: true,
    tags: ['SNS 상권', '인테리어 양호', '주거지 인근', '1층'],
    footTraffic: 3200,
    availableFrom: '2026-05-25',
    verified: true,
    featured: false,
    viewCount: 1820,
    inquiryCount: 14,
    createdAt: '2026-04-15',
    ownerType: 'direct',
    contactPhone: '010-7754-3328',
    transferorMessage: '건강 문제로 불가피하게 양도합니다. 인테리어 전부 비용 부담 없이 그대로 사용 가능합니다. 주변 카페와 달리 SNS 유입이 안정적으로 월 1,800명 수준입니다.',
    imageColors: ['#F59E0B', '#FBBF24'],
    lat: 37.5558,
    lng: 126.9232,
  },
  {
    id: 'l004',
    type: 'new',
    title: '홍대입구역 신축 상가 1층 (광장 면)',
    status: 'active',
    region: '서울',
    district: '마포구',
    fullAddress: '서울특별시 마포구 어울마당로 99',
    areaKey: 'hongdae',
    area: 32,
    floor: '1층',
    buildingType: '상가',
    deposit: 8500,
    monthlyRent: 520,
    fitCategories: ['cafe', 'snack', 'dessert', 'beverage', 'bar'],
    tags: ['역세권', '신축', '광장 면', '1층'],
    footTraffic: 8400,
    availableFrom: '2026-06-20',
    verified: true,
    featured: false,
    viewCount: 1640,
    inquiryCount: 11,
    createdAt: '2026-04-30',
    ownerType: 'agent',
    agencyName: '홍대상권부동산',
    contactPhone: '02-334-8820',
    imageColors: ['#3B82F6', '#60A5FA'],
    lat: 37.5571,
    lng: 126.9249,
  },
  {
    id: 'l005',
    type: 'transfer',
    title: '연남동 골목 디저트 카페 양도',
    status: 'active',
    region: '서울',
    district: '마포구',
    fullAddress: '서울특별시 마포구 동교로 41',
    areaKey: 'hongdae',
    area: 14,
    floor: '1층',
    buildingType: '상가',
    rightFee: 3200,
    deposit: 3500,
    monthlyRent: 210,
    fitCategories: ['dessert', 'cafe', 'beverage'],
    currentBusiness: '디저트 카페',
    monthlyRevenue: 1620,
    revenueVerified: false,
    tags: ['연남동', '인테리어 가능', '주거 인근'],
    footTraffic: 2200,
    availableFrom: '2026-05-30',
    verified: true,
    featured: false,
    viewCount: 980,
    inquiryCount: 7,
    createdAt: '2026-05-02',
    ownerType: 'direct',
    imageColors: ['#EC4899', '#F472B6'],
    lat: 37.5586,
    lng: 126.9238,
  },
  {
    id: 'l006',
    type: 'transfer',
    title: '여의도 오피스 빌딩 지하 1층 식당 양도',
    status: 'active',
    region: '서울',
    district: '영등포구',
    fullAddress: '서울특별시 영등포구 여의대로 24',
    area: 24,
    floor: '지하 1층',
    buildingType: '오피스 빌딩',
    rightFee: 3000,
    deposit: 5500,
    monthlyRent: 310,
    fitCategories: ['korean', 'japanese', 'snack', 'cafe'],
    currentBusiness: '한식 도시락',
    monthlyRevenue: 2280,
    revenueVerified: true,
    tags: ['오피스 상권', '지하 1층', '직장인 점심', '주방 설비'],
    footTraffic: 4400,
    availableFrom: '2026-05-25',
    verified: true,
    featured: false,
    viewCount: 1410,
    inquiryCount: 12,
    createdAt: '2026-04-28',
    ownerType: 'direct',
    imageColors: ['#64748B', '#94A3B8'],
    lat: 37.5219,
    lng: 126.9245,
  },
  {
    id: 'l007',
    type: 'sale',
    title: '서울 노원 상가 매각 (3층 단독)',
    status: 'active',
    region: '서울',
    district: '노원구',
    fullAddress: '서울특별시 노원구 동일로 1144',
    area: 86,
    floor: '1-3층',
    buildingType: '단독 상가',
    deposit: 0,
    monthlyRent: 0,
    salePrice: 380000,
    fitCategories: ['cafe', 'chicken', 'korean'],
    tags: ['단독 건물', '3층', '주차 6대', '주거지'],
    footTraffic: 5200,
    availableFrom: '2026-08-01',
    verified: true,
    featured: false,
    viewCount: 2150,
    inquiryCount: 18,
    createdAt: '2026-04-10',
    ownerType: 'direct',
    imageColors: ['#7C3AED', '#A78BFA'],
    lat: 37.6538,
    lng: 127.0596,
  },

  // ========= 경기/인천 =========
  {
    id: 'l008',
    type: 'new',
    title: '판교 IT 단지 1층 코너 신축 매물',
    status: 'active',
    region: '경기',
    district: '성남시 분당구',
    fullAddress: '경기도 성남시 분당구 판교역로 234',
    areaKey: 'pangyo',
    area: 14,
    floor: '1층',
    buildingType: '신축 상가',
    deposit: 5000,
    monthlyRent: 280,
    fitCategories: ['cafe', 'snack', 'korean'],
    tags: ['오피스 상권', '코너', '1층', '신축'],
    footTraffic: 4800,
    availableFrom: '2026-06-01',
    verified: true,
    featured: true,
    viewCount: 3120,
    inquiryCount: 27,
    createdAt: '2026-04-25',
    ownerType: 'agent',
    agencyName: '판교상권컨설팅',
    contactPhone: '031-781-5590',
    transferorMessage: '네이버·카카오 본사 직원 점심 수요가 주고객층입니다. 코너 위치로 유동 노출이 탁월하고 입점 즉시 영업 가능합니다. 신축 건물로 시설 상태 최상급입니다.',
    imageColors: ['#10B981', '#34D399'],
    lat: 37.3953,
    lng: 127.1117,
  },
  {
    id: 'l009',
    type: 'transfer',
    title: '인천 송도 신도시 코너 매물 양도',
    status: 'active',
    region: '인천',
    district: '연수구 송도동',
    fullAddress: '인천광역시 연수구 송도과학로 16',
    areaKey: 'songdo',
    area: 32,
    floor: '1층',
    buildingType: '상가',
    rightFee: 4200,
    deposit: 7000,
    monthlyRent: 420,
    fitCategories: ['chicken', 'korean', 'japanese', 'cafe'],
    currentBusiness: '치킨',
    monthlyRevenue: 2950,
    revenueVerified: true,
    tags: ['신도시', '코너', '대형 아파트 단지', '1층'],
    footTraffic: 5100,
    availableFrom: '2026-06-20',
    verified: true,
    featured: false,
    viewCount: 1890,
    inquiryCount: 16,
    createdAt: '2026-04-18',
    ownerType: 'direct',
    contactPhone: '010-4483-9912',
    imageColors: ['#10B981', '#059669'],
    lat: 37.3943,
    lng: 126.6528,
  },
  {
    id: 'l010',
    type: 'new',
    title: '수원 영통구 신축 상가 임대',
    status: 'active',
    region: '경기',
    district: '수원시 영통구',
    fullAddress: '경기도 수원시 영통구 영통로 200',
    area: 22,
    floor: '1층',
    buildingType: '신축 상가',
    deposit: 4500,
    monthlyRent: 280,
    fitCategories: ['cafe', 'snack', 'dessert'],
    tags: ['신축', '대로변', '주거 단지'],
    footTraffic: 3800,
    availableFrom: '2026-06-10',
    verified: true,
    featured: false,
    viewCount: 1240,
    inquiryCount: 9,
    createdAt: '2026-04-29',
    ownerType: 'agent',
    agencyName: '수원상권공인',
    imageColors: ['#3B82F6', '#60A5FA'],
    lat: 37.2584,
    lng: 127.0560,
  },
  {
    id: 'l011',
    type: 'transfer',
    title: '안양 평촌 학원가 분식점 양도',
    status: 'active',
    region: '경기',
    district: '안양시 동안구',
    fullAddress: '경기도 안양시 동안구 평촌대로 67',
    area: 16,
    floor: '1층',
    buildingType: '상가',
    rightFee: 1800,
    deposit: 3000,
    monthlyRent: 180,
    fitCategories: ['snack', 'dessert', 'beverage'],
    currentBusiness: '분식',
    monthlyRevenue: 1520,
    revenueVerified: true,
    tags: ['학원가', '학생 상권', '1층'],
    footTraffic: 2800,
    availableFrom: '2026-06-15',
    verified: true,
    featured: false,
    viewCount: 1050,
    inquiryCount: 8,
    createdAt: '2026-04-21',
    ownerType: 'direct',
    imageColors: ['#F59E0B', '#FBBF24'],
    lat: 37.3916,
    lng: 126.9566,
  },

  // ========= 부산 =========
  {
    id: 'l012',
    type: 'transfer',
    title: '해운대 신축 상가 1층 양도',
    status: 'active',
    region: '부산',
    district: '해운대구',
    fullAddress: '부산광역시 해운대구 해운대로 567',
    areaKey: 'haeundae',
    area: 22,
    floor: '1층',
    buildingType: '신축 상가',
    rightFee: 0,
    deposit: 6000,
    monthlyRent: 380,
    fitCategories: ['cafe', 'dessert', 'beverage', 'snack'],
    tags: ['신축', '관광 상권', '1층'],
    footTraffic: 5600,
    availableFrom: '2026-07-01',
    verified: true,
    featured: true,
    viewCount: 2640,
    inquiryCount: 19,
    createdAt: '2026-04-12',
    ownerType: 'agent',
    agencyName: '해운대공인',
    imageColors: ['#06B6D4', '#22D3EE'],
    lat: 35.1629,
    lng: 129.1603,
  },
  {
    id: 'l013',
    type: 'transfer',
    title: '부산 서면 1.5층 매물 양도',
    status: 'active',
    region: '부산',
    district: '부산진구',
    fullAddress: '부산광역시 부산진구 중앙대로 668',
    areaKey: 'seomyeon',
    area: 26,
    floor: '1.5층',
    buildingType: '상가',
    rightFee: 5500,
    deposit: 6000,
    monthlyRent: 350,
    fitCategories: ['bar', 'korean', 'japanese'],
    currentBusiness: '주점',
    monthlyRevenue: 3450,
    revenueVerified: true,
    tags: ['상권 중심', '1.5층', '인테리어 가능'],
    footTraffic: 7400,
    availableFrom: '2026-06-01',
    verified: true,
    featured: false,
    viewCount: 2210,
    inquiryCount: 17,
    createdAt: '2026-04-20',
    ownerType: 'direct',
    imageColors: ['#7C3AED', '#A78BFA'],
    lat: 35.1572,
    lng: 129.0593,
  },
  {
    id: 'l014',
    type: 'new',
    title: '부산 광안리 해변 신축 1층',
    status: 'active',
    region: '부산',
    district: '수영구',
    fullAddress: '부산광역시 수영구 광안해변로 220',
    area: 38,
    floor: '1층',
    buildingType: '신축 상가',
    deposit: 8500,
    monthlyRent: 480,
    fitCategories: ['cafe', 'bar', 'dessert'],
    tags: ['해변', '관광 상권', '신축', '1층'],
    footTraffic: 8200,
    availableFrom: '2026-07-15',
    verified: true,
    featured: false,
    viewCount: 1830,
    inquiryCount: 13,
    createdAt: '2026-05-03',
    ownerType: 'agent',
    agencyName: '광안리부동산',
    imageColors: ['#0EA5E9', '#38BDF8'],
    lat: 35.1530,
    lng: 129.1187,
  },

  // ========= 기타 광역 =========
  {
    id: 'l015',
    type: 'transfer',
    title: '대구 동성로 코너 카페 양도',
    status: 'active',
    region: '대구',
    district: '중구',
    fullAddress: '대구광역시 중구 동성로 134',
    areaKey: 'dongseongro',
    area: 18,
    floor: '1층',
    buildingType: '상가',
    rightFee: 3200,
    deposit: 4200,
    monthlyRent: 260,
    fitCategories: ['cafe', 'dessert', 'beverage'],
    currentBusiness: '카페',
    monthlyRevenue: 1820,
    revenueVerified: false,
    tags: ['상권 중심', '코너', '1층'],
    footTraffic: 6200,
    availableFrom: '2026-06-10',
    verified: true,
    featured: false,
    viewCount: 1340,
    inquiryCount: 11,
    createdAt: '2026-04-26',
    ownerType: 'agent',
    agencyName: '동성로상권',
    imageColors: ['#A16207', '#CA8A04'],
    lat: 35.8684,
    lng: 128.5968,
  },
  {
    id: 'l016',
    type: 'new',
    title: '대구 수성구 신축 상가 1층',
    status: 'active',
    region: '대구',
    district: '수성구',
    fullAddress: '대구광역시 수성구 동대구로 380',
    area: 24,
    floor: '1층',
    buildingType: '신축 상가',
    deposit: 4800,
    monthlyRent: 240,
    fitCategories: ['cafe', 'snack', 'korean'],
    tags: ['신축', '학원가 인근', '주거 단지'],
    footTraffic: 3400,
    availableFrom: '2026-06-25',
    verified: true,
    featured: false,
    viewCount: 920,
    inquiryCount: 6,
    createdAt: '2026-05-04',
    ownerType: 'direct',
    imageColors: ['#16A34A', '#22C55E'],
    lat: 35.8601,
    lng: 128.6318,
  },
  {
    id: 'l017',
    type: 'transfer',
    title: '대전 둔산 학원가 분식 양도',
    status: 'active',
    region: '대전',
    district: '서구 둔산동',
    fullAddress: '대전광역시 서구 둔산로 92',
    areaKey: 'dunsan',
    area: 16,
    floor: '1층',
    buildingType: '상가',
    rightFee: 1800,
    deposit: 3500,
    monthlyRent: 180,
    fitCategories: ['snack', 'dessert', 'beverage', 'cafe'],
    currentBusiness: '분식',
    monthlyRevenue: 1480,
    revenueVerified: true,
    tags: ['학원가', '학생 상권', '인테리어 양호'],
    footTraffic: 2800,
    availableFrom: '2026-06-05',
    verified: true,
    featured: false,
    viewCount: 1120,
    inquiryCount: 9,
    createdAt: '2026-04-24',
    ownerType: 'agent',
    agencyName: '둔산상권공인',
    imageColors: ['#DC2626', '#EF4444'],
    lat: 36.3504,
    lng: 127.3846,
  },
  {
    id: 'l018',
    type: 'new',
    title: '광주 충장로 신축 매물',
    status: 'active',
    region: '광주',
    district: '동구 충장로',
    fullAddress: '광주광역시 동구 충장로 88',
    areaKey: 'chungjangro',
    area: 28,
    floor: '1층',
    buildingType: '신축 상가',
    deposit: 5500,
    monthlyRent: 280,
    fitCategories: ['cafe', 'snack', 'korean', 'dessert'],
    tags: ['상권 중심', '신축', '1층'],
    footTraffic: 4400,
    availableFrom: '2026-07-05',
    verified: true,
    featured: false,
    viewCount: 880,
    inquiryCount: 5,
    createdAt: '2026-05-05',
    ownerType: 'direct',
    imageColors: ['#0EA5E9', '#38BDF8'],
    lat: 35.1523,
    lng: 126.9162,
  },
  {
    id: 'l019',
    type: 'transfer',
    title: '울산 삼산동 치킨 매장 양도',
    status: 'active',
    region: '울산',
    district: '남구 삼산동',
    fullAddress: '울산광역시 남구 삼산로 240',
    areaKey: 'ulsan_samsan',
    area: 30,
    floor: '1층',
    buildingType: '상가',
    rightFee: 3500,
    deposit: 6500,
    monthlyRent: 360,
    fitCategories: ['chicken', 'korean', 'snack', 'bar'],
    currentBusiness: '치킨',
    monthlyRevenue: 2820,
    revenueVerified: true,
    tags: ['상권 중심', '주차 가능', '주방 설비'],
    footTraffic: 4200,
    availableFrom: '2026-07-15',
    verified: true,
    featured: false,
    viewCount: 760,
    inquiryCount: 6,
    createdAt: '2026-04-19',
    ownerType: 'agent',
    agencyName: '울산상권부동산',
    imageColors: ['#EA580C', '#F97316'],
    lat: 35.5384,
    lng: 129.3114,
  },
  {
    id: 'l020',
    type: 'sale',
    title: '제주 함덕 상가 매각',
    status: 'active',
    region: '제주',
    district: '제주시 조천읍 함덕리',
    fullAddress: '제주특별자치도 제주시 조천읍 함덕로 1234',
    area: 64,
    floor: '1-2층',
    buildingType: '상가 (양옆 노출)',
    deposit: 0,
    monthlyRent: 0,
    salePrice: 280000,
    fitCategories: ['cafe', 'korean'],
    tags: ['해변 인근', '관광 상권', '2개층'],
    footTraffic: 4800,
    availableFrom: '2026-09-01',
    verified: true,
    featured: false,
    viewCount: 1620,
    inquiryCount: 12,
    createdAt: '2026-04-08',
    ownerType: 'direct',
    imageColors: ['#0EA5E9', '#06B6D4'],
    lat: 33.5444,
    lng: 126.7013,
  },
  {
    id: 'l021',
    type: 'new',
    title: '서울 영등포 오피스 빌딩 1층 임대',
    status: 'active',
    region: '서울',
    district: '영등포구',
    fullAddress: '서울특별시 영등포구 국제금융로 25',
    area: 38,
    floor: '1층',
    buildingType: '오피스 빌딩',
    deposit: 9500,
    monthlyRent: 550,
    fitCategories: ['cafe', 'korean', 'japanese'],
    tags: ['오피스 상권', '대로변', '1층'],
    footTraffic: 6800,
    availableFrom: '2026-08-01',
    verified: true,
    featured: false,
    viewCount: 1450,
    inquiryCount: 10,
    createdAt: '2026-04-30',
    ownerType: 'agent',
    agencyName: '여의도공인',
    imageColors: ['#475569', '#64748B'],
    lat: 37.5214,
    lng: 126.9241,
  },
  {
    id: 'l022',
    type: 'transfer',
    title: '강동구 천호동 한식당 양도',
    status: 'active',
    region: '서울',
    district: '강동구',
    fullAddress: '서울특별시 강동구 천호대로 1095',
    area: 36,
    floor: '1층',
    buildingType: '상가',
    rightFee: 4500,
    deposit: 5500,
    monthlyRent: 320,
    fitCategories: ['korean', 'japanese', 'snack'],
    currentBusiness: '한식당',
    monthlyRevenue: 2640,
    revenueVerified: true,
    tags: ['주거 인근', '주차 가능', '주방 설비'],
    footTraffic: 4100,
    availableFrom: '2026-06-25',
    verified: true,
    featured: false,
    viewCount: 1180,
    inquiryCount: 8,
    createdAt: '2026-04-27',
    ownerType: 'direct',
    imageColors: ['#16A34A', '#22C55E'],
    lat: 37.5477,
    lng: 127.1394,
  },
  {
    id: 'l023',
    type: 'new',
    title: '인천 부평구 신축 상가 1층',
    status: 'active',
    region: '인천',
    district: '부평구',
    fullAddress: '인천광역시 부평구 부평대로 78',
    area: 26,
    floor: '1층',
    buildingType: '신축 상가',
    deposit: 5200,
    monthlyRent: 290,
    fitCategories: ['cafe', 'snack', 'korean', 'chicken'],
    tags: ['역세권', '신축', '1층'],
    footTraffic: 4400,
    availableFrom: '2026-07-10',
    verified: true,
    featured: false,
    viewCount: 1080,
    inquiryCount: 7,
    createdAt: '2026-05-06',
    ownerType: 'agent',
    agencyName: '부평상권공인',
    imageColors: ['#10B981', '#059669'],
    lat: 37.4895,
    lng: 126.7228,
  },
  {
    id: 'l024',
    type: 'transfer',
    title: '서울 종로 한정식 매물 양도',
    status: 'active',
    region: '서울',
    district: '종로구',
    fullAddress: '서울특별시 종로구 종로 124',
    area: 44,
    floor: '1-2층',
    buildingType: '상가',
    rightFee: 6500,
    deposit: 7500,
    monthlyRent: 450,
    fitCategories: ['korean', 'bar'],
    currentBusiness: '한정식',
    monthlyRevenue: 3650,
    revenueVerified: true,
    tags: ['관광 상권', '2개층', '주방 설비'],
    footTraffic: 5800,
    availableFrom: '2026-07-01',
    verified: true,
    featured: false,
    viewCount: 1340,
    inquiryCount: 9,
    createdAt: '2026-04-23',
    ownerType: 'direct',
    imageColors: ['#A16207', '#CA8A04'],
    lat: 37.5727,
    lng: 126.9791,
  },
  // ========= 신촌 =========
  {
    id: 'l026',
    type: 'transfer',
    title: '신촌역 도보 3분, 1층 카페 양도',
    status: 'active',
    region: '서울',
    district: '서대문구',
    fullAddress: '서울특별시 서대문구 연세로 39',
    areaKey: 'sinchon',
    area: 16,
    floor: '1층',
    buildingType: '상가',
    rightFee: 3800,
    deposit: 5000,
    monthlyRent: 290,
    fitCategories: ['cafe', 'beverage', 'dessert'],
    currentBusiness: '카페',
    monthlyRevenue: 2050,
    revenueVerified: true,
    tags: ['역세권', '대학가', '1층', 'SNS 상권'],
    footTraffic: 5800,
    availableFrom: '2026-06-20',
    verified: true,
    featured: false,
    viewCount: 1640,
    inquiryCount: 12,
    createdAt: '2026-05-01',
    ownerType: 'direct',
    imageColors: ['#6366F1', '#818CF8'],
    lat: 37.5548,
    lng: 126.9365,
  },
  // ========= 이태원 =========
  {
    id: 'l027',
    type: 'new',
    title: '이태원 경리단길 신규 임대 1층',
    status: 'active',
    region: '서울',
    district: '용산구',
    fullAddress: '서울특별시 용산구 회나무로 55',
    areaKey: 'itaewon',
    area: 28,
    floor: '1층',
    buildingType: '상가',
    deposit: 7500,
    monthlyRent: 480,
    fitCategories: ['bar', 'cafe', 'korean', 'japanese'],
    tags: ['경리단길', '외국인 상권', '1층', '대로변'],
    footTraffic: 6100,
    availableFrom: '2026-07-01',
    verified: true,
    featured: false,
    viewCount: 1280,
    inquiryCount: 9,
    createdAt: '2026-05-03',
    ownerType: 'agent',
    agencyName: '용산상권부동산',
    imageColors: ['#B45309', '#D97706'],
    lat: 37.5344,
    lng: 126.9948,
  },
  // ========= 건대입구 =========
  {
    id: 'l028',
    type: 'transfer',
    title: '건대입구 먹자골목 주점 양도',
    status: 'active',
    region: '서울',
    district: '광진구',
    fullAddress: '서울특별시 광진구 능동로 55',
    areaKey: 'konkuk',
    area: 22,
    floor: '2층',
    buildingType: '상가',
    rightFee: 4200,
    deposit: 5500,
    monthlyRent: 310,
    fitCategories: ['bar', 'chicken', 'snack', 'korean'],
    currentBusiness: '주점',
    monthlyRevenue: 3120,
    revenueVerified: true,
    tags: ['먹자골목', '야간 상권', '2층', '인테리어 양호'],
    footTraffic: 7800,
    availableFrom: '2026-06-01',
    verified: true,
    featured: false,
    viewCount: 2140,
    inquiryCount: 18,
    createdAt: '2026-04-28',
    ownerType: 'direct',
    imageColors: ['#7C3AED', '#A78BFA'],
    lat: 37.5401,
    lng: 127.0706,
  },
  // ========= 잠실 =========
  {
    id: 'l029',
    type: 'new',
    title: '잠실역 인근 신축 상가 1층 카페 임대',
    status: 'active',
    region: '서울',
    district: '송파구',
    fullAddress: '서울특별시 송파구 석촌호수로 184',
    areaKey: 'jamsil',
    area: 34,
    floor: '1층',
    buildingType: '신축 상가',
    deposit: 10500,
    monthlyRent: 640,
    fitCategories: ['cafe', 'dessert', 'beverage', 'korean'],
    tags: ['역세권', '신축', '코너', '대로변'],
    footTraffic: 8800,
    availableFrom: '2026-07-15',
    verified: true,
    featured: true,
    viewCount: 2980,
    inquiryCount: 24,
    createdAt: '2026-04-30',
    ownerType: 'agent',
    agencyName: '잠실상권컨설팅',
    imageColors: ['#0891B2', '#06B6D4'],
    lat: 37.5133,
    lng: 127.1001,
  },
  // ========= 명동 =========
  {
    id: 'l030',
    type: 'transfer',
    title: '명동 관광 상권 디저트 매장 양도',
    status: 'active',
    region: '서울',
    district: '중구',
    fullAddress: '서울특별시 중구 명동8가길 23',
    areaKey: 'myeongdong',
    area: 20,
    floor: '1층',
    buildingType: '상가',
    rightFee: 9000,
    deposit: 10000,
    monthlyRent: 750,
    fitCategories: ['dessert', 'snack', 'cafe', 'beverage'],
    currentBusiness: '디저트 (타이야키)',
    monthlyRevenue: 5200,
    revenueVerified: true,
    tags: ['관광 상권', '외국인 집중', '1층', '대로변'],
    footTraffic: 12000,
    availableFrom: '2026-06-15',
    verified: true,
    featured: true,
    viewCount: 4120,
    inquiryCount: 32,
    createdAt: '2026-04-20',
    ownerType: 'direct',
    imageColors: ['#DC2626', '#EF4444'],
    lat: 37.5636,
    lng: 126.9845,
  },
  // ========= 성수동 =========
  {
    id: 'l031',
    type: 'transfer',
    title: '성수동 카페 골목 프리미엄 카페 양도',
    status: 'active',
    region: '서울',
    district: '성동구',
    fullAddress: '서울특별시 성동구 서울숲2길 44',
    areaKey: 'seongsu',
    area: 26,
    floor: '1층',
    buildingType: '상가',
    rightFee: 7200,
    deposit: 8000,
    monthlyRent: 560,
    fitCategories: ['cafe', 'dessert', 'beverage'],
    currentBusiness: '스페셜티 카페',
    monthlyRevenue: 4100,
    revenueVerified: false,
    tags: ['SNS 상권', '카페 골목', '인테리어 고급', '1층'],
    footTraffic: 5200,
    availableFrom: '2026-06-30',
    verified: true,
    featured: false,
    viewCount: 3320,
    inquiryCount: 26,
    createdAt: '2026-04-25',
    ownerType: 'agent',
    agencyName: '성수상권',
    imageColors: ['#6D28D9', '#7C3AED'],
    lat: 37.5443,
    lng: 127.0562,
  },
  // ========= 수원 인계동 =========
  {
    id: 'l032',
    type: 'transfer',
    title: '수원 인계동 1층 코너 한식당 양도',
    status: 'active',
    region: '경기',
    district: '수원시 팔달구',
    fullAddress: '경기도 수원시 팔달구 인계로 118',
    areaKey: 'suwon_ingye',
    area: 24,
    floor: '1층',
    buildingType: '상가',
    rightFee: 3000,
    deposit: 4500,
    monthlyRent: 230,
    fitCategories: ['korean', 'bar', 'snack'],
    currentBusiness: '한식 백반',
    monthlyRevenue: 2200,
    revenueVerified: true,
    tags: ['코너', '주차 가능', '저녁 상권', '주방 설비'],
    footTraffic: 4600,
    availableFrom: '2026-06-10',
    verified: true,
    featured: false,
    viewCount: 1180,
    inquiryCount: 10,
    createdAt: '2026-05-02',
    ownerType: 'direct',
    imageColors: ['#059669', '#10B981'],
    lat: 37.2620,
    lng: 127.0275,
  },
  // ========= 전주 객사 =========
  {
    id: 'l033',
    type: 'new',
    title: '전주 객사 한옥마을 인근 1층 임대',
    status: 'active',
    region: '전북',
    district: '전주시 완산구',
    fullAddress: '전라북도 전주시 완산구 전주객사5길 28',
    areaKey: 'jeonju_gaeksa',
    area: 18,
    floor: '1층',
    buildingType: '한옥 상가',
    deposit: 3000,
    monthlyRent: 160,
    fitCategories: ['korean', 'dessert', 'cafe'],
    tags: ['한옥마을 인근', '관광 상권', '1층', 'SNS 상권'],
    footTraffic: 4800,
    availableFrom: '2026-06-25',
    verified: true,
    featured: false,
    viewCount: 890,
    inquiryCount: 6,
    createdAt: '2026-05-05',
    ownerType: 'agent',
    agencyName: '전주상권공인',
    imageColors: ['#A16207', '#CA8A04'],
    lat: 35.8224,
    lng: 127.1488,
  },
  // ========= 제주 연동 =========
  {
    id: 'l034',
    type: 'transfer',
    title: '제주 연동 카페 거리 디저트 카페 양도',
    status: 'active',
    region: '제주',
    district: '제주시 연동',
    fullAddress: '제주특별자치도 제주시 연동 무근성7길 14',
    areaKey: 'jeju_yeon',
    area: 20,
    floor: '1층',
    buildingType: '상가',
    rightFee: 3600,
    deposit: 4500,
    monthlyRent: 240,
    fitCategories: ['cafe', 'dessert', 'beverage'],
    currentBusiness: '감귤 디저트 카페',
    monthlyRevenue: 2640,
    revenueVerified: true,
    tags: ['카페 거리', '관광객 동선', '인테리어 양호', '1층'],
    footTraffic: 4200,
    availableFrom: '2026-07-01',
    verified: true,
    featured: false,
    viewCount: 1420,
    inquiryCount: 11,
    createdAt: '2026-04-22',
    ownerType: 'direct',
    imageColors: ['#F97316', '#FB923C'],
    lat: 33.4891,
    lng: 126.4982,
  },
  // ========= 대전 은행동 =========
  {
    id: 'l035',
    type: 'new',
    title: '대전 은행동 상권 1층 신규 임대',
    status: 'active',
    region: '대전',
    district: '중구 은행동',
    fullAddress: '대전광역시 중구 은행로 68',
    areaKey: 'daejeon_eunhaengdong',
    area: 22,
    floor: '1층',
    buildingType: '상가',
    deposit: 3500,
    monthlyRent: 190,
    fitCategories: ['korean', 'cafe', 'snack', 'bar'],
    tags: ['상권 중심', '직장인 상권', '1층', '주차 가능'],
    footTraffic: 5200,
    availableFrom: '2026-06-15',
    verified: true,
    featured: false,
    viewCount: 740,
    inquiryCount: 5,
    createdAt: '2026-05-07',
    ownerType: 'agent',
    agencyName: '대전중구상권',
    imageColors: ['#0EA5E9', '#38BDF8'],
    lat: 36.3278,
    lng: 127.4276,
  },

  {
    id: 'l025',
    type: 'sale',
    title: '경기 일산 상가 매각 (1층 카페 운영중)',
    status: 'active',
    region: '경기',
    district: '고양시 일산동구',
    fullAddress: '경기도 고양시 일산동구 정발산로 25',
    area: 38,
    floor: '1층',
    buildingType: '상가',
    deposit: 0,
    monthlyRent: 0,
    salePrice: 210000,
    fitCategories: ['cafe', 'snack', 'dessert'],
    tags: ['주거 단지', '카페 운영 중', '1층'],
    footTraffic: 3600,
    availableFrom: '2026-08-15',
    verified: true,
    featured: false,
    viewCount: 1490,
    inquiryCount: 11,
    createdAt: '2026-04-16',
    ownerType: 'agent',
    agencyName: '일산상권부동산',
    imageColors: ['#7C3AED', '#A78BFA'],
    lat: 37.6649,
    lng: 126.7866,
  },
]

// 일부 양도 매물에 양도인 메시지 부여 (자료 풍부도 향상)
const TRANSFEROR_MESSAGES: Record<string, string> = {
  l001: '7년 운영했던 매장으로 단골 비중 60% 이상입니다. 본사 협의 후 동종 인수 시 권리금 협상 가능.',
  l003: '오픈 1년차 매장으로 인테리어 컨디션이 매우 좋습니다. 주방 설비 그대로 사용 가능.',
  l005: '개인 사정으로 양도합니다. 단골 위주 매장이라 인수 후 매출 안정성이 높습니다.',
  l006: '오피스 푸드코트 자리로 평일 점심 매출이 안정적입니다. 평일 영업만으로 충분히 손익이 맞습니다.',
  l009: '아파트 단지 코너로 가족 단위 손님이 많습니다. 주방 시설 추가 투자 없이 인수 가능합니다.',
  l011: '학원가 한복판에 위치해 학생 손님이 꾸준합니다. 본사 협의 시 분식 외 업종 운영도 가능.',
  l013: '동성로 한복판 1.5층 자리로 야간 상권이 강합니다. 주점·라멘 등 야간 운영에 적합.',
  l015: '청년층 핫플레이스 골목 코너입니다. SNS 노출이 잘 되는 위치.',
  l017: '학원가 + 청사 객수가 시간대별로 분산되어 회전율이 좋습니다.',
  l019: '주방 시설 그대로 인수 가능합니다. 치킨 외 한식·분식 운영도 가능한 입지.',
  l022: '주거지 인근이라 평일·주말 매출이 균형 잡혀 있습니다. 주차 가능.',
  l024: '관광 상권에 위치한 2개층 한정식 매장. 외국인 손님 비중 30% 이상.',
  l026: '신촌역 바로 앞 골목 카페입니다. 단골 대학생 비중이 높아 매출이 안정적입니다.',
  l028: '건대 먹자골목 핵심 위치입니다. 주방 시설 그대로 인수 가능하며 야간 객수 보장.',
  l030: '명동 관광 동선 한복판 매장입니다. 외국인 단체 관광 루트에 위치해 평일에도 만석.',
  l031: '성수 카페 골목 코어에 위치합니다. SNS 바이럴로 대기 손님이 꾸준하고 인스타 노출 입지.',
  l032: '15년 운영 백반집입니다. 인근 직장인 고정 손님 확보되어 있어 점심 매출이 안정적.',
  l034: '제주 카페 거리에서도 손꼽히는 감귤 디저트 카페입니다. 관광객·이주민 모두 단골.',
}

const _OWN_LISTINGS: MockListing[] = RAW_LISTINGS.map((l) => ({
  ...l,
  images: listingPhotoSet(l.id, l.fitCategories),
  transferorMessage: TRANSFEROR_MESSAGES[l.id],
}))

// ─────────────────────────────────────────────────────────────────
// 외부 출처 매물 통합
//
// changupmall.com 등 외부 사이트에서 수집한 매물을 MockListing 형태로 변환해
// 자체 매물과 동일 리스트에 합친다. 외부 출처는 externalSource 필드로 구분.
// 추가 사이트는 동일 패턴으로 외부 JSON을 import 후 변환 함수 한 번만 호출.
// ─────────────────────────────────────────────────────────────────

type CmListingRaw = {
  sourceId: string
  url: string
  title: string
  type: ListingType
  region: string
  district: string
  fullAddress: string
  area: number
  rawSize: string
  rawIndustry: string
  rightFee?: number
  monthlyRevenue?: number
  monthlyExpense?: number
  monthlyProfit?: number
  fitCategories: string[]
  currentBusiness: string
  photos: string[]
}

type CmJson = {
  source: string
  label: string
  fetchedAt: string
  listings: CmListingRaw[]
}

function fromChangupmall(json: CmJson): MockListing[] {
  return json.listings
    // 최소 정보(제목·위치) 없는 매물 스킵
    .filter((r) => r.title && r.region)
    .map((r): MockListing => ({
      id: `cm${r.sourceId}`,
      type: r.type,
      title: r.title,
      status: 'active',
      region: r.region,
      district: r.district,
      fullAddress: r.fullAddress || `${r.region} ${r.district}`.trim(),
      area: r.area || 0,
      floor: '',
      buildingType: '',
      rightFee: r.rightFee,
      // 창업몰은 보증금/월세를 따로 안 줌. 권리금/수익만 노출. 0으로 둠.
      deposit: 0,
      monthlyRent: 0,
      fitCategories: r.fitCategories,
      currentBusiness: r.currentBusiness,
      monthlyRevenue: r.monthlyRevenue,
      revenueVerified: false,
      tags: [],
      footTraffic: 0,
      availableFrom: '협의',
      verified: false,
      featured: false,
      viewCount: 0,
      inquiryCount: 0,
      createdAt: json.fetchedAt.slice(0, 10),
      ownerType: 'agent',
      agencyName: json.label,
      imageColors: ['#e5e7eb', '#f3f4f6'],
      images: r.photos,
      externalSource: {
        name: json.source,
        label: json.label,
        sourceId: r.sourceId,
        url: r.url,
        fetchedAt: json.fetchedAt,
      },
    }))
}

const _CHANGUPMALL = fromChangupmall(cmRaw as CmJson)

export const LISTINGS: MockListing[] = [..._OWN_LISTINGS, ..._CHANGUPMALL]

export const FEATURED_LISTINGS = LISTINGS.filter((l) => l.featured)
export const TRANSFER_LISTINGS = LISTINGS.filter((l) => l.type === 'transfer')
export const NEW_LISTINGS = LISTINGS.filter((l) => l.type === 'new')
export const SALE_LISTINGS = LISTINGS.filter((l) => l.type === 'sale')

/** Top-N popular listings by view count. */
export function popularListings(limit = 6): MockListing[] {
  return [...LISTINGS].sort((a, b) => b.viewCount - a.viewCount).slice(0, limit)
}

export function listingsByArea(areaKey: string): MockListing[] {
  return LISTINGS.filter((l) => l.areaKey === areaKey)
}
